name : CI - Build
on : 
  pull_request:
    branches: ["main"]

jobs: 
  build_test:
    runs-on: ubuntu-latest
    steps:
      - name : Checkout repo
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
  build_doble:
      runs-on: ubuntu-latest
      needs: test_code
      steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Ant
        run: ant -noinput -buildfile build.xml

        
  test_code:
    runs-on: ubuntu-latest
    needs: build_test
    steps:
    - name : Checkout repo
      uses: actions/checkout@v3
    - name: Test with Maven
      run: mvn test --file pom.xml
