name : CI - Build
on : 
  pull_request:
    branches: ["main"]
  push:
    branches:
      - main
jobs: 
  build_test:
    runs-on: ubuntu-latest
    steps:
      - name : Checkout repo
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

        
  test_code:
    runs-on: ubuntu-latest
    needs: build_test
    steps:
    - name : Checkout repo
      uses: actions/checkout@v3
    - name: Test with Maven
      run: mvn test --file pom.xml


  publish_code:
    runs-on: ubuntu-latest
    needs: test_code
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}

