name : CI - Build
on : 
  pull_request:
    branches: ["main"]

jobs: 
  build_test:
    runs-on: ubuntu-latest
    steps:
      - name : Checkout repo
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
  test_code:
    runs-on: ubuntu-latest
    needs: build_test
    steps:
    - name : Checkout repo
      uses: actions/checkout@v3
    - name: Test with Maven
      run: mvn test --file pom.xml
